config/routes.rb
Hmage::Application.routes.draw do
  devise_for :users

  resources :maps, only: [:index, :show, :edit, :update] do
    member do
      get 'location'
      post 'set_grids'
    end
    collection do
      post 'search'
      post 'related'
      post 'overlap'
    end
  end

  namespace :admin do
    resources :users, only: [:index] do
      collection do
        get  'list'
        post 'search'
        post 'update'
      end
    end
  end

  resources :names do
    collection do
      get  'list'
      post 'search'
      get  'find'
      get  'importer'
      post 'import'
    end
  end

  resources :tickets do
    collection do
      get 'downloads'
      get 'updates'
      get 'rejected'
      get 'opened'
      get 'accepted'
      get 'expired'
    end
  end

  match '/about', :to => redirect('/index.html')
  match '*unmatched_route', :to => 'application#raise_not_found!'

end

app/models/name.rb
class Name < ActiveRecord::Base
  attr_accessible :current, :original, :description, :latlon
  validates :original, :uniqueness => true
  validates :current, :original, :latlon, presence: true, :on => :create

  paginates_per 15

  # PostgreSQL full-text search
  include PgSearch
  pg_search_scope :search_by_attributes,
                  :against => [:original, :current, :description],
                  :using => {
                    :tsearch => {:prefix => true}
                  }

  pg_search_scope :search_by_name,
                  :against => [:original, :current],
                  :using => {
                    :tsearch => {:prefix => true}
                  }

  def latlon
    factory = RGeo::Cartesian.factory
    coordinates = read_attribute(:latlon)
    coordinates ||= factory.parse_wkt("POINT(0 0)")
  end

end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :find, :search]
  load_and_authorize_resource

  def list
    @names = Name.order("current").page(params[:page])
  end

  def search
    @names = Name.search_by_attributes(params[:q])
  end

  def find
    @names = Name.search_by_name(params[:q])
    respond_to do |format|
      format.html
      format.json { render :json => @names }
    end
  end

  def new
    @name = Name.new
  end

  def create
    @name = Name.new(params[:name])
    @name.save!
    redirect_to name_path(@name), :notice => "SAVE NAME OK."
  rescue Exception => ex
    render action: "new"
  end

  def show
    @name = Name.find(params[:id])
  end

  def edit
    @name = Name.find(params[:id])
  end

  def update
    @name = Name.find(params[:id])
    if @name.update_attributes!(params[:name])
      redirect_to name_path(@name), :notice => "SAVE NAME OK."
    else
      render edit_name_path
    end
  rescue Exception => ex
    render action: "edit"
  end

end

app/helpers/names_helper.rb
module NamesHelper
end

app/views/names/_form.html.erb
<%= form_for name, :html => {:class => "form-horizontal", :role => "form"} do |f| %>
  <%= render "shared/error_messages", :target => name %>
  <div class="form-group">
    <div class="col-sm-3">
      <%= f.label :original, :class => "control-label" %>
    </div>
    <div class="col-sm-9">
      <%= f.text_field :original, :class => "form-control", :placeholder => t(:placeholder_original, :scope => [:name]), :type => "text", :required => true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-3">
      <%= f.label :current, :class => "control-label" %>
    </div>
    <div class="col-sm-9">
      <%= f.text_field :current, :class => "form-control", :placeholder => t(:placeholder_current, :scope => [:name]), :type => "text", :required => true %>
    </div>
  </div>
  <hr>
  <div class="form-group">
      <%= cktext_area :name, :description, :cols => 40, :ckeditor => {:toolbar => 'mini'} %>
  </div>

  <%= f.hidden_field :latlon %>

  <div class="form-group">
    <div class="col-sm-6">
      <%= link_to t(:cancel, :scope => [:application]), :back, :class => "btn btn-primary btn-block" %>
    </div>
    <div class="col-sm-6">
      <%= f.submit t(:save, :scope => [:application]), :class => "btn btn-primary btn-block", :onclick => "return setNameWkt();" %>
    </div>
  </div>
<% end %>

app/views/names/_name.html.erb
<table class="table table-condensed">
  <tbody>
    <tr>
      <th><%= Name.human_attribute_name("current") %></th>
      <td><%= name.current %></td>
    </tr>
    <tr>
      <th><%= Name.human_attribute_name("original") %></th>
      <td><%= name.original %></td>
    </tr>
    <tr>
      <td colspan="2">
        <% unless name.description.nil? %>
          <%= name.description.html_safe %>
        <% else %>
          <div class="well" style="height:300px;"></div>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

app/views/names/_names.html.erb
<table class="table table-striped table-condensed" id="names_table">
  <thead>
    <th><%= Name.human_attribute_name("original") %></th>
    <th><%= Name.human_attribute_name("current") %></th>
    <th><%= Name.human_attribute_name("latlon") %></th>
  </thead>
  <tbody>
    <% names.each do |name| %>
    <tr>
      <td>
        <%= link_to name.original, name_path(name) %>
      </td>
      <td>
        <%= link_to name.current, name_path(name) %>
      </td>
      <td>
        <% unless name.latlon.x == 0 and name.latlon.y == 0 %>
          <i class="fa fa-location-arrow"></i>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
  <tfoot>
    <td colspan="4">
      <center><%= paginate names %></center>
    </td>
  </tfoot>
</table>

app/views/names/_results.html.erb
<% if names.size > 0 %>
  <table class="table table-striped table-condensed" id="names_table">
    <thead>
      <th><%= Name.human_attribute_name("original") %></th>
      <th><%= Name.human_attribute_name("current") %></th>
      <th><%= Name.human_attribute_name("latlon") %></th>
    </thead>
    <tbody>
      <% names.each do |name| %>
      <tr>
        <% if name.latlon.x == 0 and name.latlon.y == 0 %>
          <td>
            <%= link_to name.original, name_path(name) %>
          </td>
        <% else %>
          <td class="draggable" data-value="<%= name.original %>" data-point="(<%= name.latlon.y %> <%= name.latlon.x  %>)">
            <%= link_to name.original, name_path(name) %>
          </td>
        <% end %>
        <td>
          <%= link_to name.current, name_path(name) %>
        </td>
        <td id="<%= name.original %>">
          <% unless name.latlon.x == 0 and name.latlon.y == 0 %>
            <i class="fa fa-location-arrow"></i>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
    <div class="jumbotron">
      <div class="hero-unit center">
        <h1><%= t(:names_not_found, :scope => [:application]) %></h1>
      </div>
    </div>
<% end %>

app/views/names/edit.html.erb
<script type="text/javascript">
    $(document).ready(function() {
      init();

      markersLayer = new OpenLayers.Layer.Markers("Markers");
      map.addLayers([markersLayer]);

      var lat = '<%= raw @name.latlon.x %>';
      var lon = '<%= raw @name.latlon.y %>';
      if(lat != 0 && lon != 0){
        setLocation(lat, lon);
      }

      $('#geocode_btn').click(function(){
        var address = document.getElementById('address').value;
        getLatLng(address);
      });
    });
</script>
<div class="row">
  <br>
  <div class="col-md-6">
    <%= render :partial => 'form', :locals => {:name => @name} %>
  </div>
  <div class="col-md-6">
    <div class="form-group">
      <div class="input-group">
        <div class="input-group-addon">Address</div>
        <input type="address" class="form-control" id="address" placeholder="Budapest, Hungary">
        <div class="input-group-btn">
          <button id="geocode_btn" class="btn btn-primary">Geocode</button>
        </div>
      </div>
    </div>
    <div id="map" class="smallmap"></div>
  </div>
</div>

app/views/names/index.html.erb
<script type="text/javascript">
  var points = [];
  $(function() {
    $('.droppable').droppable({
      drop: function( event, ui ) {
        points.push(ui.draggable.attr("data-point"));
        $('#towns_table tbody').append("<tr><td>" + ui.draggable.attr("data-value") + "</td></tr>");
      }
    });

    // Initialize Openlayers Maps
    $("#map").attr("class", "smallmap");
    init();
    console.log("Openlayers Maps loaded");

  });
</script>
<div class="row">
  <hr>
  <!-- Search by Towns -->
  <div class="col-md-7">
    <!-- Search Towns Form -->
    <%= form_tag search_names_path, :class => "form", :role => "search", :remote => true  do %>
    <div class="input-group">
      <%= text_field_tag :q, nil, :class => "form-control", :placeholder => t(:placeholder_search, :scope => [:name]), :type => "text" %>
      <div class="input-group-btn">
        <%= button_tag(type: "submit", class: "btn btn-default") do %>
          <i class="glyphicon glyphicon-search"></i> <%= t(:search, :scope => [:application]) %>
        <% end %>
      </div>
    </div>
    <% end %>
    <br>
    <div id="mapContainer">
      <div id='map'></div>
    </div>
    <br>
  </div>

  <!-- Selected Towns list -->
  <div class="col-md-5">
    <div class="caption">
      <h4><%= t(:search_result, :scope => [:name]) %></h4>
      <div id="townsContainer">
        <div class="jumbotron">
          <div class="hero-unit center">
            <h1></h1>
          </div>
        </div>
      </div>
    </div>
    <hr>

    <div class="caption droppable">
      <h4><%= t(:search_town_title, :scope => [:name]) %></h4>
      <p>
        <table id="towns_table" class="table table-bordered table-striped overflow: auto">
          <thead>
            <th>Location Name</th>
          </thead>
          <tbody>
          </tbody>
        </table>
      </p>
    </div>

    <%= form_tag overlap_maps_path, :class => "navbar-form", :role => "search"  do %>
        <%= hidden_field_tag 'points_geometry' %>
        <%= button_tag(type: "submit", :onclick => "return setPointsData();", class: "btn btn-primary btn-block") do %>
          <i class="glyphicon glyphicon-map-marker"></i> &nbsp;
          <%= t(:search, :scope => [:application]) %>
        <% end %>
    <% end %>


  </div>
</div>

app/views/names/list.html.erb
<div class="row">
  <div class="well">
    <%= form_tag search_names_path, :class => "form", :role => "search", :remote => true  do %>
    <div class="input-group">
      <%= text_field_tag :q, nil, :class => "form-control", :placeholder => t(:search_placeholder, :scope => [:application]), :type => "text" %>
      <div class="input-group-btn">
        <%= button_tag(type: "submit", class: "btn btn-default") do %>
          <i class="glyphicon glyphicon-search"></i> <%= t(:search, :scope => [:application]) %>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

<div class="row" id="mapContainer">
  <div id='map'></div>
</div>
<br>
<div class="row" id="townsContainer">
  <%= render :partial => 'names', :locals => {:names => @names} %>
</div>

app/views/names/new.html.erb
<script type="text/javascript">
    $(document).ready(function() {
      init();

      markersLayer = new OpenLayers.Layer.Markers("Markers");
      map.addLayers([markersLayer]);

      var lat = '<%= raw @name.latlon.x %>';
      var lon = '<%= raw @name.latlon.y %>';
      if(lat != 0 && lon != 0){
        setLocation(lat, lon);
      }

      $('#geocode_btn').click(function(){
        var address = document.getElementById('address').value;
        getLatLng(address);
      });
    });
</script>
<div class="row">
  <br>
  <div class="col-md-6">
    <%= render :partial => 'form', :locals => {:name => @name} %>
  </div>
  <div class="col-md-6">
    <div class="form-group">
      <div class="input-group">
        <div class="input-group-addon">Address</div>
        <input type="address" class="form-control" id="address" placeholder="Budapest, Hungary">
        <div class="input-group-btn">
          <button id="geocode_btn" class="btn btn-primary">Geocode</button>
        </div>
      </div>
    </div>
    <div id="map" class="smallmap"></div>
  </div>
</div>

app/views/names/search.js.erb
// Insert results table
$('#townsContainer').html("<%= escape_javascript render(:partial => 'results', :locals => {:names => @names}) %>");

if(map == null){
  // Initialize Openlayers Maps
  $("#map").attr("class", "smallmap");
  init();
  markersLayer = new OpenLayers.Layer.Markers("Markers");
  map.addLayers([markersLayer]);
  console.log("Openlayers Maps loaded");
}else{
  // Remove All the Markers
  markersLayer.clearMarkers();
  console.log("Clear all markers");
}

<% @names.each do |name| %>
  if('<%= raw name.latlon %>' != 'POINT (0.0 0.0)'){
    var feature = wkt.read('<%= raw name.latlon %>');
    var point = new OpenLayers.Geometry.Point(feature.geometry.y, feature.geometry.x).transform(map.displayProjection, map.getProjectionObject());
    var marker = new OpenLayers.Marker(new OpenLayers.LonLat(point.x, point.y), icon.clone());
    markersLayer.addMarker(marker);;
  }
  map.zoomToExtent(markersLayer.getDataExtent());
<% end %>
console.log("Points loaded");


$('.draggable').draggable({helper: "clone"});

app/views/names/show.html.erb
<script type="text/javascript">
    $(document).ready(function() {
      init();

      markersLayer = new OpenLayers.Layer.Markers("Markers");
      map.addLayers([markersLayer]);

      var lat = '<%= raw @name.latlon.x %>';
      var lon = '<%= raw @name.latlon.y %>';
      if(lat != 0 && lon != 0){
        setLocation(lat, lon);
      }
    });
</script>
<div class="row">
  <br>
  <div class="col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h3><%= t(:caption_header, :scope => [:name]) %></h3>

        <p>
          <%= render :partial => 'name', :locals => {:name => @name} %>
        </p>
        <% if can? :manage, Name %>
          <div class="media">
            <%= link_to edit_name_path(@name), :class => "pull-left" do %>
              <i class="glyphicon glyphicon-th-list media-object" style="font-size:64px;"></i>
            <% end %>

            <div class="media-body">
              <h4 class="media-heading"><%= t(:set_attributes, :scope => [:name]) %></h4>
              Updating current or original name, set location for current Town.
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div id="map" class="smallmap"></div>
  </div>
</div>