config/routes.rb
Hmage::Application.routes.draw do
  devise_for :users

  resources :maps, only: [:index, :show, :edit, :update] do
    member do
      get 'location'
      post 'set_grids'
    end
    collection do
      post 'search'
      post 'related'
      post 'overlap'
    end
  end

  namespace :admin do
    resources :users, only: [:index] do
      collection do
        get  'list'
        post 'search'
        post 'update'
      end
    end
  end

  resources :names do
    collection do
      get  'list'
      post 'search'
      get  'find'
      get  'importer'
      post 'import'
    end
  end

  resources :tickets do
    collection do
      get 'downloads'
      get 'updates'
      get 'rejected'
      get 'opened'
      get 'accepted'
      get 'expired'
    end
  end

  match '/about', :to => redirect('/index.html')
  match '*unmatched_route', :to => 'application#raise_not_found!'

end

app/models/map.rb
class Map < ActiveRecord::Base
  attr_accessible :name, :path, :image, :kind, :size, :resolution, :publisher,
                  :downloadable, :processed, :year, :section, :theme, :projection, :description,
                  :creator, :participante, :language, :remarks, :source, :gridding, :physical_size

  belongs_to :map_groups
  has_many :grids, dependent: :destroy
  has_many :tickets
  paginates_per 10

  # PostgreSQL full-text search
  include PgSearch
  pg_search_scope :search_by_attributes,
                  :against => [:name, :kind, :size, :resolution, :publisher,
                               :year, :section, :theme, :projection, :description,
                               :creator, :participante, :language, :remarks, :source],
                  :using => {
                    :tsearch => {:prefix => true}
                  }

  # Paperclip configuration
  has_attached_file :image,
    :styles => {
      :thumb  => '100x100>',
      :medium => '500x375>',
      :large   => '1000x1000>',
    },
    :default_url => "/missing.png",
    :path => "/var/data/hmage/system/:style/:filename.:extension",
    :url  => "/system/:style/:filename.:extension"

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  #
  # Get all Processed images
  #
  def Map.processed(page)
    self.where(processed: true).page(page).per(AppConstants.maps_per_page)
  end

  #
  # Get all unprocessed images.
  #
  def Map.unprocessed(page)
    self.where(processed: false).page(page).per(AppConstants.maps_per_page)
  end

  def wkt_polygons
    polygons = []
    self.grids.each do |grid|
      polygons << {name: grid.grid_id, bbox: grid.bbox.as_text}
    end
    return polygons
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :related, :overlap, :search]

  def show
    @map = Map.find(params[:id])
    @grids = (params[:grids].nil?) ? [].to_json : params[:grids]
    @polygons = @map.wkt_polygons.to_json
    @active_download_tickets = Ticket.can_user_request_download_ticket(current_user.id, params[:id])
    @active_update_tickets = Ticket.can_user_request_update_ticket(current_user.id, params[:id])
    @mapgroup = MapGroup.find(@map.id)
    @download_ticket = Ticket.new(map_id: @map.id, user_id: current_user.id, request_type: 'DOWNLOAD')
    @update_ticket = Ticket.new(map_id: @map.id, user_id: current_user.id, request_type: 'UPDATE')
  end

  def edit
    @map = Map.find(params[:id])
    @mapgroup = MapGroup.find(@map.id)
    authorize! :edit, @map
  end

  def location
    @map = Map.find(params[:id])
    @polygons = @map.wkt_polygons.to_json

    authorize! :location, @map
  end

  def set_grids
    @map = Map.find(params[:id])
    @map.grids.destroy_all
    factory = RGeo::Cartesian.factory

    params[:grids].each do |grid, value|
      unless value.empty?
        polygon = factory.parse_wkt(value)
        @map.grids.create(:grid_id => grid, :bbox => polygon)
      end
    end

    authorize! :set_grids, @map
    redirect_to map_path
  rescue Exception => e
    flash[:notice] = "There was a problem Settings Grids on map: #{e.message}."
    render :action => :location
  end

  def update
    @map = Map.find(params[:id])
    @map.update_attributes!(params[:map])

    authorize! :update, @map
    redirect_to map_path
  rescue Exception => e
    flash[:notice] = "There was a problem updating map: #{e.message}."
    render :action => :edit
  end

  def search
    if params[:q].eql?("all")
      @maps = Map.all
    else
      session[:query] = params[:q]
      @maps = Map.search_by_attributes(params[:q])
    end
  end

  def related
    @grids = Grid.st_relate(params[:geometry])
    @maps = []
    @grids.each_key do |key|
      @maps << Map.find(key)
    end
  end

  def overlap
    if params[:points_geometry]
      @geometry = params[:points_geometry]
    else
      @geometry = params[:point_geometry]
    end
    @grids = Grid.st_overlap(@geometry)
    @maps = []
    @grids.each_key do |key|
      @maps << Map.find(key)
    end
  end
end

app/helpers/maps_helper.rb
module MapsHelper
  def status_to_icon(status)
    if status
      "fa fa-check-square-o icon pull-right".html_safe
    else
      "fa fa-square-o icon pull-right".html_safe
    end
  end

  def status_to_text(status)
    if status
      Map.human_attribute_name("processed").html_safe
    else
      Map.human_attribute_name("unprocessed").html_safe
    end
  end
end

app/views/maps/_grids.html.erb
<script type="text/javascript">
  $(document).ready(function(){
      $(".map-image").elevateZoom({
        scrollZoom : true,
        responsive:  true,
        loadingIcon: true
      });
  });
</script>
<% unless maps.blank? %>
  <% maps.each do |map| %>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 ">
          <div class="panel panel-default">
              <div class="row padall">
                  <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                      <span></span>
                        <img id="<%= map.id %>" src="<%= map.image.url(:thumb) %>" data-zoom-image="<%= map.image.url(:medium) %>" class="img-responsive img-rounded map-image" />

                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
                      <div class="clearfix">
                          <div class="pull-left">
                              <span class="fa fa-paperclip icon"> <%= number_to_human_size(map.image.size) %></span>
                          </div>
                          <div class="pull-right">
                             <%= map.theme %> | <%= map.language %> | <%= map.resolution %>
                          </div>
                      </div>
                      <div>
                          <h4>
                            <% if can? :read, Map%>
                              <%= link_to map.name, :controller => :maps, :action => :show, :id => map.id, :grids => grids[map.id] %>
                            <% else %>
                              <%= map.name %>
                            <% end %>
                          </h4>
                          <span class="fa fa-bank icon"></span>  <%= map.publisher %>
                          <span class="<%= status_to_icon(map.processed) %>"><%= status_to_text(map.processed) %></span>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  <% end %>
<% else %>
    <div class="jumbotron">
      <div class="hero-unit center">
        <h1><%= t(:names_not_found, :scope => [:application]) %></h1>
      </div>
    </div>
<% end %>

app/views/maps/_maps.html.erb
<script type="text/javascript">
  $(document).ready(function(){
      $(".map-image").elevateZoom({
        scrollZoom : true,
        responsive:  true,
        loadingIcon: true
      });

      $(".fancybox-thumb").fancybox({
        prevEffect  : 'none',
        nextEffect  : 'none',
        helpers : {
          title : {
            type: 'outside'
          },
          thumbs  : {
            width : 50,
            height  : 50
          }
        }
      });

  });
</script>
<% if maps.size > 0 %>
  <div class="row">
      <div class="col-lg-12">
            <div class="well well-sm">
                <strong>Search results: <%= session[:query] %></strong>
            </div>
      </div>
  </div>
  <div id="maps" class="row list-group">
  <% maps.each do |map| %>
        <div class="item col-xs-4 col-lg-4">
            <div class="thumbnail">
                <div class="caption">
                    <h4 class="group inner list-group-item-heading">
                      <% if can? :read, Map %>
                        <%= link_to map.name, map_path(map.id) %>
                      <% else %>
                        <%= map.name %>
                      <% end %>
                    </h4>
                    <p class="group inner list-group-item-text"><%= truncate(map.description, length: 200) %></p>
                    <div class="row">
                        <div class="col-xs-12 col-md-12">
                          <table class="table table-striped table-condensed">
                            <tr>
                              <td>Type</td>
                              <td><%= map.theme %></td>
                            </tr>
                            <tr>
                              <td>Language</td>
                              <td><%= map.language %></td>
                            </tr>
                            <tr>
                              <td>Publisher</td>
                              <td><%= map.publisher %></td>
                            </tr>
                            <tr>
                              <td>Size</td>
                              <td><%= number_to_human_size(map.image.size) %></td>
                            </tr>
                            <tr>
                              <td>Preview</td>
                              <td>
                                <a class="fancybox-thumb" rel="fancybox-thumb" href="<%= map.image.url(:large) %>" title="<%= map.name %>">
                                  <span id="<%= map.id %>" class="glyphicon glyphicon-eye-open" data-url="<%= map.image.url(:medium) %>"></span>
                                </a>
                              </td>
                            </tr>
                          </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
  <% end %>
  </div>
<% else %>
    <div class="jumbotron">
      <div class="hero-unit center">
        <h1><%= t(:names_not_found, :scope => [:application]) %></h1>
      </div>
    </div>
<% end %>

app/views/maps/index.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    init();
    $('[data-toggle="popover"]').popover()
    console.log("ENDO");
  });
</script>

<div id="editMapFormDiv" class="row">
  <!-- LEFT MENU -->
  <div class="col-md-3">
    <div class="profile-sidebar">
      <!-- SIDEBAR USERPIC -->
      <div class="profile-userpic">
        <!--<center><a data-toggle="modal" class="btn btn-circle-lg btn-info"><i class="fa fa-info"></i> </a></center>-->
      </div>
      <!-- END SIDEBAR USERPIC -->
      <!-- SIDEBAR USER TITLE -->
      <div class="profile-usertitle">
        <div class="profile-usertitle-name">
          <%= t(:search_by_map, :scope => [:map]) %>
        </div>
      </div>
      <!-- END SIDEBAR USER TITLE -->
      <!-- SIDEBAR MENU -->
      <div class="profile-usermenu">
        <ul id="mapInfoPanel" class="nav">
          <li>
            <a href="javascript:void(0)" onclick="toggleControl('polygon');">
              <i class="glyphicon glyphicon-edit"></i>
              <%= t(:draw_polygon, :scope => [:map]) %>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)" onclick="toggleControl('box');">
              <i class="glyphicon glyphicon-stop"></i>
              <%= t(:draw_rectangle, :scope => [:map]) %>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)" onclick="toggleControl('nav');">
              <i class="glyphicon glyphicon-screenshot"></i>
              <%= t(:move_map, :scope => [:map]) %>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)" onclick="toggleControl('edit');">
              <i class="glyphicon glyphicon-wrench"></i>
              <%= t(:edit_feature, :scope => [:map]) %>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)" onclick="toggleControl('select');">
              <i class="glyphicon glyphicon-hand-up"></i>
              <%= t(:select_feature, :scope => [:map]) %>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)" onclick="removeFeature();">
              <i class="glyphicon glyphicon-minus-sign"></i>
              <%= t(:remove_feature, :scope => [:map]) %>
            </a>
          </li>
          <li>
            <a>
              <%= form_tag related_maps_path, :class => "navbar-form"  do %>
                <%= hidden_field_tag 'geometry' %>
                <%= button_tag(type: "submit", :onclick => "return setMapData();", class: "btn btn-info") do %>
                    <i class="fa fa-search"></i>
                    <%= t(:search_by_map, :scope => [:application]) %>
                <% end %>
              <% end %>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- CONTENT -->    
  <div class="col-md-9">
        <!-- Search by Town Names Form -->
        <%= form_tag overlap_maps_path, :class => "navbar-form", :role => "search"  do %>
        <div class="input-group">
          <%= hidden_field_tag 'point_geometry' %>
          <input class="typeahead form-control" id="q" name="q" placeholder="<%= t(:placeholder_search, :scope => [:name]) %>" type="text" data-provide="typeahead" autofocus />

          <div class="input-group-btn">
            <%= button_tag(type: "submit", class: "btn btn-success") do %>
              <%= t(:search, :scope => [:application]) %>
            <% end %>
          </div>
        </div>
        <% end %>

        <div id="map" class="smallmap border-radius"></div>
  </div>
</div>

app/views/maps/location.html.erb
<script type="text/javascript">
  var polygons = JSON.parse('<%= raw @polygons %>');
  var wkt = new OpenLayers.Format.WKT();
  var viewMode = true;

  $(document).ready(function(){
      var lastClicked;
      var clickedGrid;

      ////////////////////////////////////////////////////////////////////////////////
      /**
       * SET DEFAULT GRID SIZE 2X2
       */
      var grid = clickableGrid(2,2,function(el,row,col,i){
        el.className='clicked';
        if (lastClicked){
          lastClicked.className='';
        }
        lastClicked = el;
        clickedGrid = el.innerHTML;
        currentFeatureLabel = clickedGrid;
      });
      // ADD GRIDS TO MAP IMAGE
      $('#grid-source').append(grid);

      /**
       * GRID ON IMAGE AND FEATURE ON MAP.
       */
      $("#gridNameForm").submit(false);
      $("#gridNameForm").submit(function(event){
          var gridName = $("#gridNameTxt").val();
          
          if(gridName != clickedGrid){
            alert("Invalid Grid Name");
          }else{
            selectedFeature.attributes = {grid: gridName};
            var str = formats['out']['wkt'].write(selectedFeature, false);
            $("#grids_"+gridName).val(str);
            vectorLayer.redraw();
          }
      });

      var gridSliderValue = $('#gridsizeSelect').change(function(ev){
        $("#grid").remove();
        $(".wkt_grids").remove();

        var gridSize = $(this).val();
        var newGrid = clickableGrid(gridSize,gridSize,function(el,row,col,i){
          el.className='clicked';
          if (lastClicked){
            lastClicked.className='';
          }
          lastClicked = el;
          clickedGrid = el.innerHTML;
          currentFeatureLabel = clickedGrid;
        });

        for(i = 1; i <= gridSize*gridSize; i++ ){
          $("#editMapFormDiv").append('<input class="wkt_grids" id="grids_A' + i + '" name="grids[A' + i + ']" type="hidden" value="" />');
        }
        $("#grid-source").html("");
        $("#grid-source").append(newGrid);
      });
      ////////////////////////////////////////////////////////////////////////////////

      init();

      ////////////////////////////////////////////////////////////////////////////////
      /**
       * ADD EXISTING FEATURES ON MAP
       */
      for(idx in polygons){
        polygon = polygons[idx];
        var feature = wkt.read(polygon.bbox);
        feature.attributes = {
          grid: polygon.name
        };
        feature.geometry.transform(map.displayProjection, map.getProjectionObject());
        vectorLayer.addFeatures([feature]);
      }
      // ZOOM TO FEATURES EXTENT
      if(polygons.length > 0){
        map.zoomToExtent(vectorLayer.getDataExtent());
      }
      ////////////////////////////////////////////////////////////////////////////////

      ////////////////////////////////////////////////////////////////////////////////
      /**
       * MAGNIFIER SETTINGS
       */
      var image = $("#<%= @map.id %>");
      var magnifier = $("#magnifier");
      var magnifier_status = $("#magnifier_status");
      var magnifier_label = $("#magnifier_label");
      var zoomConfig = {
              zoomType: "lens",
              lensShape: "round",
              lensSize: 400,
              scrollZoom : true,
              responsive:  true,
              loadingIcon: true
            };
      var zoomActive = false;
      magnifier.on('click', function(){
          zoomActive = !zoomActive;
          if(zoomActive){
               image.elevateZoom(zoomConfig);//initialise zoom
               magnifier_status.attr("class", "fa fa-check-square-o icon pull-right");
               magnifier_label.html("<%= t(:magnifier_on, :scope => [:application]) %>");
          }else{
              $.removeData(image, 'elevateZoom');//remove zoom instance from image
              $('.zoomContainer').remove();// remove zoom container from DOM
              magnifier_status.attr("class", "fa fa-square-o icon pull-right");
              magnifier_label.html("<%= t(:magnifier_off, :scope => [:application]) %>");
          }
      });
      ////////////////////////////////////////////////////////////////////////////////

      console.log("END");

  });

function setData(){
  var features = vectorLayer.features;
  for(idx in features){
    var feature = features[idx];
    var wkt = formats['out']['wkt'].write(feature, false);
    $("#grids_" + feature.attributes.grid).val(wkt);
  }
  $(".form-horizontal").submit();
}


</script>

<div id="editMapFormDiv" class="row">
<%= form_tag set_grids_map_path, :class => "form-horizontal", :role => "form" do %>
  <!-- LEFT MENU -->
  <div class="col-md-3">
    <div class="profile-sidebar">
      <!-- SIDEBAR USERPIC -->
      <div class="profile-userpic">
        <!--<center><a data-toggle="modal" class="btn btn-circle-lg btn-info"><i class="fa fa-info"></i> </a></center>-->
      </div>
      <!-- END SIDEBAR USERPIC -->
      <!-- SIDEBAR USER TITLE -->
      <div class="profile-usertitle">
        <div class="profile-usertitle-name">
          <%= t(:tools, :scope => [:map]) %>
        </div>
      </div>
      <!-- END SIDEBAR USER TITLE -->
      <!-- SIDEBAR MENU -->
      <div class="profile-usermenu">
        <ul id="mapInfoPanel" class="nav">
          <li>
            <a>
              <i class="glyphicon glyphicon-th"></i>
              <%= t(:grid_size, :scope => [:map]) %>:
              <select id="gridsizeSelect">
                <option>1</option>
                <option selected="selected">2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
              </select>
            </a>
          </li>
          <li id="magnifier">
            <a>
              <i class="glyphicon glyphicon-zoom-in"></i>
              <%= t(:magnifier, :scope => [:application]) %>
              <abbr id="magnifier_label"><%= t(:magnifier_off, :scope => [:application]) %></abbr>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)" onclick="toggleControl('polygon');">
              <i class="glyphicon glyphicon-edit"></i>
              <%= t(:draw_polygon, :scope => [:map]) %>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)" onclick="toggleControl('box');">
              <i class="glyphicon glyphicon-stop"></i>
              <%= t(:draw_rectangle, :scope => [:map]) %>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)" onclick="toggleControl('nav');">
              <i class="glyphicon glyphicon-screenshot"></i>
              <%= t(:move_map, :scope => [:map]) %>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)" onclick="toggleControl('edit');">
              <i class="glyphicon glyphicon-wrench"></i>
              <%= t(:edit_feature, :scope => [:map]) %>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)" onclick="toggleControl('select');">
              <i class="glyphicon glyphicon-hand-up"></i>
              <%= t(:select_feature, :scope => [:map]) %>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)" onclick="removeFeature();">
              <i class="glyphicon glyphicon-minus-sign"></i>
              <%= t(:remove_feature, :scope => [:map]) %>
            </a>
          </li>

          <li>
            <%= link_to '#', :onclick => 'return setData();' do %>
              <i class="glyphicon glyphicon-floppy-disk"></i>
              <%= t(:save_modifications, :scope => [:application]) %>
            <% end %>
          </li>
          <li>
            <%= link_to map_path(@map.id) do %>
              <i class="glyphicon glyphicon-remove-circle"></i>
              <%= t(:cancel, :scope => [:application]) %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- CONTENT -->    
  <div class="col-md-9">
    <div class="img-overlay">
      <img id="<%= @map.id %>" src="<%= @map.image.url(:large) %>" data-zoom-image="<%= @map.image.url(:large) %>" class="img-responsive img-rounded" />
      <div id="grid-source" class="grid-overlay"></div>
    </div>
  </div>
  <div id="map" class="smallmap"></div>
  <%= hidden_field_tag 'grids[A1]', '', class: 'wkt_grids' %>
  <%= hidden_field_tag 'grids[A2]', '', class: 'wkt_grids' %>
  <%= hidden_field_tag 'grids[A3]', '', class: 'wkt_grids' %>
  <%= hidden_field_tag 'grids[A4]', '', class: 'wkt_grids' %>
<% end %>
</div>

app/views/maps/overlap.html.erb
<div class="row">
  <br>
  <%= render :partial => 'grids', :locals => {:maps => @maps, :grids => @grids} %>
</div>

app/views/maps/related.html.erb
<div class="row">
  <br>
  <%= render :partial => 'maps', :locals => {:maps => @maps} %>
</div>

app/views/maps/search.html.erb
<div class="row">
  <br>
  <%= render :partial => 'maps', :locals => {:maps => @maps} %>
</div>