config/routes.rb
Hmage::Application.routes.draw do
  devise_for :users

  resources :maps, only: [:index, :show, :edit, :update] do
    member do
      get 'location'
      post 'set_grids'
    end
    collection do
      post 'search'
      post 'related'
      post 'overlap'
    end
  end

  namespace :admin do
    resources :users, only: [:index] do
      collection do
        get  'list'
        post 'search'
        post 'update'
      end
    end
  end

  resources :names do
    collection do
      get  'list'
      post 'search'
      get  'find'
      get  'importer'
      post 'import'
    end
  end

  resources :tickets do
    collection do
      get 'downloads'
      get 'updates'
      get 'rejected'
      get 'opened'
      get 'accepted'
      get 'expired'
    end
  end

  match '/about', :to => redirect('/index.html')
  match '*unmatched_route', :to => 'application#raise_not_found!'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tickets, dependent: :destroy
  ROLES = %w[admin editor viewer librarian]
  paginates_per 10

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable
  validates_uniqueness_of :email, :on => :create
  validates :name, :email, :password, presence: true, :on => :create
  validates :password, :presence =>true, :confirmation => true, :on => :create

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :role
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def list
    @users = User.where("role <> 'admin'").order(:email).page params[:page]
  end

  def search
    if params[:role]
      @users = User.where("role like '%#{params[:role]}%'")
    elsif params[:name]
      @users = User.where("name like '%#{params[:name]}%'")
    else
      @users = User.where("email like '%#{params[:email]}%'")
    end
  end

  def update
    User.update(params['users'].keys, params['users'].values)
    redirect_to list_admin_users_path
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_users.html.erb
<%= form_tag(admin_users_path, :role => 'form') do %>
<div class="panel panel-primary">
  <div class="panel-heading"><%= t(:manage_users, :scope => [:application]) %></div>
  <div class="panel-body">
    <table class="table table-responsive">
      <thead>
        <th>User Name</th>
        <th>Email Address</th>
        <th>Created at</th>
        <th>Role</th>
        <th>Action</th>
      </thead>
      <tbody>
        <% for user in users %>
        <tr class="active">
          <%= fields_for "users[]", user do |f| %>
            <td><%=h user.name %></td>
            <td><%=h user.email %></td>
            <td><%=h user.created_at.strftime("%Y-%B-%e") %></td>
            <td><span class="label label-success"><%=h user.role %></span></td>
            <td><%= f.collection_select :role, User::ROLES, :to_s, :humanize, {:selected => user.role}, :class => 'form-control' %></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="5">
            
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
  <div class="panel-footer">
    <%= submit_tag "Submit", :class => "btn btn-primary btn-block" %>    
  </div>
</div>
<% end %>

app/views/admin/users/list.html.erb
<div class="row profile">
  <!-- Search by Name -->
  <div class="col-md-4">
    <br>
    <%= form_tag search_admin_users_path, :class => "form", :role => "search", :remote => true do %>
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-user"></i>
        </span>
        <%= text_field_tag :name, nil, :class => "form-control", :placeholder => User.human_attribute_name('name'), :type => "text" %>
        <div class="input-group-btn">
          <%= button_tag(type: "submit", class: "btn btn-success") do %>
            <%= t(:search, :scope => [:application]) %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Search by email address -->
  <div class="col-md-4">
    <br>
    <%= form_tag search_admin_users_path, :class => "form", :role => "search", :remote => true do %>
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-envelope-o"></i>
        </span>
        <%= text_field_tag :email, nil, :class => "form-control", :placeholder => User.human_attribute_name('email'), :type => "text" %>
        <div class="input-group-btn">
          <%= button_tag(type: "submit", class: "btn btn-success") do %>
            <%= t(:search, :scope => [:application]) %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <!-- Search by user role -->
  <div class="col-md-4">
    <br>
    <%= form_tag search_admin_users_path, :class => "form", :role => "search", :remote => true do %>
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-lock"></i>
        </span>
        <%= select_tag "role", options_for_select([ "viewer", "editor", "librarian", "admin"], "viewer"), :class => "form-control" %>
        <div class="input-group-btn">
          <%= button_tag(type: "submit", class: "btn btn-success") do %>
            <%= t(:search, :scope => [:application]) %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div id="users_list" class="row">

</div>

app/views/admin/users/search.js.erb
// Insert results table
$('#users_list').html("<%= escape_javascript render(:partial => 'users', :locals => {:users => @users}) %>");