config/routes.rb
Hmage::Application.routes.draw do
  devise_for :users

  resources :maps, only: [:index, :show, :edit, :update] do
    member do
      get 'location'
      post 'set_grids'
    end
    collection do
      post 'search'
      post 'related'
      post 'overlap'
    end
  end

  namespace :admin do
    resources :users, only: [:index] do
      collection do
        get  'list'
        post 'search'
        post 'update'
      end
    end
  end

  resources :names do
    collection do
      get  'list'
      post 'search'
      get  'find'
      get  'importer'
      post 'import'
    end
  end

  resources :tickets do
    collection do
      get 'downloads'
      get 'updates'
      get 'rejected'
      get 'opened'
      get 'accepted'
      get 'expired'
    end
  end

  match '/about', :to => redirect('/index.html')
  match '*unmatched_route', :to => 'application#raise_not_found!'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Historical maps Geolocator</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href="/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <script src="http://maps.google.com/maps/api/js?v=3&sensor=false"></script>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="background-dark ">
  <br><br>
  <div class="navbar navbar-default navbar-fixed-bottom swag-line swag-line-bottom">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">G.R.I.D</a>
    </div>
    <ul class="nav navbar-nav">
      <!-- USER AND ACCOUNT MANAGEMENT -->
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
          <small class="text-muted">
            <% if user_signed_in? %>
              <%= current_user.role %>
            <% else %>
              <%= t(:guest_user, :scope => [:application]) %>
            <% end %>
          </small>
          <div>
            <% if user_signed_in? %>
              <%= current_user.name %>
            <% else %>
              ..................
            <% end %>
            &nbsp;&nbsp;&nbsp;&nbsp;
          </div>
          <span class="caret up"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
          <% if user_signed_in? %>
            <!-- USER ADMINISTRATION -->
            <% if can? :manage, User %>
              <li>
                <%= link_to list_admin_users_path do %>
                  <%= t(:manage_users, :scope => [:application]) %>
                <% end %>
              </li>
              <li class="divider"></li>
            <% end %>
            <!-- ACCOUNT MANAGEMENT -->
            <li>
              <%= link_to edit_user_registration_path do %>
                <%= t(:change_password, :scope => [:application]) %>
              <% end %>
            </li>
            <li class="divider"></li>
            <!-- SIGN OUT -->
            <li>
              <%= link_to destroy_user_session_path, :method => 'delete' do %>
                <%= t(:signout, :scope => [:application]) %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to t(:signin, :scope => [:application]) ,new_user_session_path %>
            </li>
          <% end %>
        </ul>
      </li>
      <!-- TICKET MANAGEMENT -->
      <% if can? :create, Ticket or can? :update, Ticket %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
          <small class="text-muted">management</small>
          <div>Tickets&nbsp;&nbsp;</div>
          <span class="caret up"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
          <% unless current_user.role == 'librarian' %>
          <li>
            <%= link_to downloads_tickets_path do %>
              <i class="fa fa-cloud-download"></i> &nbsp; <%= t(:my_requests_download, :scope => [:application]) %>
            <% end %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to updates_tickets_path do %>
              <i class="glyphicon glyphicon glyphicon-exclamation-sign"></i> &nbsp; <%= t(:my_requests_update, :scope => [:application]) %>
            <% end %>            
          </li>
          <li class="divider"></li>
          <% end %>
          <li>
            <%= link_to opened_tickets_path(:page => 0) do %>
              <i class="glyphicon glyphicon-question-sign"></i> &nbsp; <%= t(:open_requests, :scope => [:ticket]) %>
            <% end %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to accepted_tickets_path(:page => 0) do %>
              <i class="glyphicon glyphicon-ok-circle"></i> &nbsp; <%= t(:accepted_requests, :scope => [:ticket]) %>
            <% end %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to rejected_tickets_path(:page => 0) do %>
              <i class="glyphicon glyphicon-ban-circle"></i> &nbsp; <%= t(:rejected_requests, :scope => [:ticket]) %>
            <% end %>
          </li>
          <% if current_user.role == 'librarian' %>
            <li class="divider"></li>
            <li>
            <%= link_to expired_tickets_path(:page => 0) do %>
              <i class="glyphicon glyphicon-time"></i> &nbsp; <%= t(:expired_requests, :scope => [:ticket]) %>
            <% end %>
            </li>
          <% end %>
        </ul>
      </li>      
      <% end %>
      <!-- TOWN MANAGEMENT -->
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
          <small class="text-muted">management</small>
          <div><%= t(:menu_towns, :scope => [:application]) %>&nbsp;&nbsp;</div>
          <span class="caret up"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
          <li>
            <%= link_to names_path do %>
              <%= t(:search_by_towns, :scope => [:application]) %>
            <% end %>
          </li>
          <% if can? :manage, Name %>
            <li class="divider"></li>
            <li>
              <%= link_to list_names_path do %>
                <%= t(:manage_towns, :scope => [:application]) %>
              <% end %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to new_name_path do %>
                <%= t(:add_town, :scope => [:application]) %>
              <% end %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to importer_names_path do %>
                <%= t(:import_towns, :scope => [:application]) %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </li>
      <li>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      </li>
    </ul>    
    
    <%= form_tag search_maps_path, :class => "navbar-form", :role => "search"  do %>
    <div class="input-group">
      <%= text_field_tag :q, nil, :class => "form-control", :placeholder => t(:search_placeholder, :scope => [:application]), :type => 'text', :autofocus => true %>
      <span class="input-group-btn">
        <%= button_tag(type: "submit", class: "btn btn-default") do %>
          <%= t(:search, :scope => [:application]) %>
        <% end %>
      </span>
    </div>
    <% end %>

  </div>
  <div class="container">
    <%= yield %>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>
  </div>
  <script type="text/javascript">
  $(document).ready(function(){

    var towns = new Bloodhound({
      datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      remote: {
        url: '../names/find?q=%QUERY',
        filter: function (towns) {
            console.log(towns);
            return $.map(towns, function (town) {
                console.log(town.latlon);
                var points = town.latlon.replace("POINT ","").replace("(","").replace(")","").split(" ");
                console.log(points);
                return {
                    value: town.original + " - ( " + town.current + " )",
                    coordinates: "(" + points[1] + " " + points[0] + ")"
                };
            });
        }
      }
    });

    towns.initialize();

    $('#q.typeahead').typeahead(null, {
      name: 'towns_names',
      displayKey: 'value',
      source: towns.ttAdapter(),
      templates: {
        empty: [
          '<div class="alert alert-success" role="alert">',
          '<%= t(:names_not_found, :scope => [:application]) %>',
          '</div>'
        ].join('\n')
      }
    }).bind("typeahead:selected", function(datum, obj, name) {
      var wkt = "MULTIPOINT(" + obj.coordinates + ")";
      $('#point_geometry').val(wkt);
      console.log(wkt)
    });
  });
  </script>
</body>
</html>